development:
  adapter: postgresql
  database: openoverflow_development
  host: localhost
  username: postgres
  password: 

test:
  adapter: postgresql
  database: openoverflow_test
  host: localhost
  username: postgres
  password: 

production:
  adapter: postgresql
  database: openoverflow_production
  host: localhost
  username: postgres
  password: 

